controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_car_reviews:
    path: '/api/car/{carId}/reviews'
    methods: ['GET']
    defaults:
        _controller: '\App\Controller\ReviewController::getLatestReviews'